cursor #cacaca
cursor_text_color #a2a2a2

foreground            #cacaca
background            #131313
selection_foreground  #211602
selection_background  #46381e
url_color             #cf9926

color0   #131313
color1   #f6331e
color2   #3fcf26
color3   #ffd819
color4   #c48703
color5   #4e3600
color6   #cf9926
color7   #d9d2c4
color8   #464238
color9   #ff6f62
color10  #7ff86a
color11  #ffe66d
color12  #e3b145
color13  #ffd06d
color14  #ffe1a1
color15  #fffbf4
