cursor #cacaca
cursor_text_color #a2a2a2

foreground            #cacaca
background            #131313
selection_foreground  #231503
selection_background  #49371f
url_color             #da932e

color0   #131313
color1   #fa3021
color2   #49da2e
color3   #ffd921
color4   #cf7e0b
color5   #543300
color6   #da932e
color7   #e4dccf
color8   #464139
color9   #ff7268
color10  #88ff72
color11  #ffe772
color12  #efad4e
color13  #ffc472
color14  #ffd9a4
color15  #fffbf4
