context.properties = {
    default.clock.rate          = 192000
    default.clock.allowed-rates = [ 44100 48000 88200 96000 176400 192000 ]
    
    # Reducimos a un Quantum dinámico para permitir que el buffer se recupere
    default.clock.quantum       = 1024
    default.clock.min-quantum   = 512
    default.clock.max-quantum   = 2048
    
    # Desactivamos el forzado agresivo que causa clipping en USB
    node.force-quantum = 0
    node.force-rate    = 0
    
    mem.allow-mlock             = true
}

context.modules = [
    { name = libpipewire-module-rt
      args = {
          nice.level   = -15
          rt.prio      = 88
          # Valores estándar para estabilidad en USB
          rt.time.soft = 500000
          rt.time.hard = 500000
      }
      flags = [ ifexists nofail ]
    }
]