context.properties = {
    ## Forzamos el reloj maestro a 192kHz sin alternativas
    default.clock.rate          = 192000
    default.clock.allowed-rates = [ 192000 ]
    
    ## Forzamos a que el sistema use este Quantum incluso si la app pide otro
    node.force-quantum = 2048
    node.force-rate    = 192000

    ## Quantum fijo para evitar fluctuaciones a alta frecuencia
    ## 2048 a 192kHz nos da una estabilidad de ~10.6ms
    default.clock.quantum       = 2048
    default.clock.min-quantum   = 2048
    default.clock.max-quantum   = 8192
    
    ## Aseguramos que PipeWire no relaje estas reglas
    settings.check-quantum      = true
    settings.check-rate         = true
    
    ## Bloqueo de memoria para evitar que el kernel mueva el audio al swap
    mem.allow-mlock             = true
}

context.modules = [
    { name = libpipewire-module-rt
      args = {
          nice.level    = -15
          rt.prio       = 88
          ## Aumentamos los tiempos de respuesta para el i9-13900K
          rt.time.soft  = 200000
          rt.time.hard  = 200000
          ## Forzamos el uso de P-Cores mediante uclamp
          uclamp.min    = 1024
          uclamp.max    = 1024
      }
      flags = [ ifexists nofail ]
    }
]