pulse.rules = [
    {
        matches = [ { application.process.binary = "waydroid" } ]
        actions = {
            update-props = {
                # Forzamos a Waydroid a hablar el idioma de la RME
                node.latency = 2048/192000
                pulse.min.req = 2048/192000
                pulse.min.quantum = 2048/192000
            }
        }
    }
]
