-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(da932e)",
			inactive_border = "rgb(828282)",
		},
	},
	group = {
		col = {
			border_active = "rgb(da932e)",
			border_inactive = "rgb(828282)",
			border_locked_active = "rgb(ff796c)",
			border_locked_inactive = "rgb(828282)",
		},
		groupbar = {
			col = {
				active = "rgb(da932e)",
				inactive = "rgb(828282)",
				locked_active = "rgb(ff796c)",
				locked_inactive = "rgb(828282)",
			},
		},
	},
})
