-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Amber")
hl.env("XCURSOR_THEME", "Bibata-Modern-Amber")
hl.env("HYPRCURSOR_SIZE", "29")
hl.env("XCURSOR_SIZE", "29")
